Repository krook1024/SZFM_2020_1_KP_B1G, pull requests merged in 2020-10, with the labels that each got.

#24 Requirement specification - Paragraph 2. Closes #2
  doc/kovspec.md
Labels: documentation

#25 Functional specification - Paragraph 11. Closes #18
  doc/funkspec.md
Labels: documentation

#26 Kovspec jelenlegi uzletifolyamatok modellje, Closes #3
  doc/kovspec.md
Labels: documentation

#28 Functional specification - Paragraph 7. Closes #14
  doc/funkspec.md
  doc/img/screen_design/cars-listed.png
  doc/img/screen_design/login.png
  doc/img/screen_design/register.png
  doc/img/screen_design/rent-car.png
Labels: documentation

#27 Kovspec szabalyok
  doc/kovspec.md
Labels: documentation

#43 Fixing title of the paragraph
  doc/kovspec.md
Labels: fix

#48 Funkspec. jelenlegi üzletifolyamatok modellje
  doc/diagram/funkspec_felhasználókezelés.txt
  doc/diagram/funkspec_szerviz_beszerz.txt
  doc/funkspec.md
  doc/img/funkspec_felhasznalokezeles.png
  doc/img/funkspec_szerviz_beszerz.png
Labels: documentation

#45 Added 7. paragraph of requirement specification. Closes #7
  doc/diagram/ks_autobeszerzes.txt
  doc/diagram/ks_felhasznalokezeles.txt
  doc/diagram/ks_karbantartas.txt
  doc/diagram/ks_kolcsonzes.txt
  doc/funkspec.md
  doc/kovspec.md
Labels: documentation

#47 Funkspec szabályok és rendeletek
  doc/funkspec.md
Labels: documentation

#52 Funkspec vagyalom rendszer
  doc/funkspec.md
  doc/rendszerspec.md
Labels: documentation

#51 Rendszerterv rendszer celja
  doc/rendszerspec.md
Labels: documentation

#53 Rendszerterv Karbantartás
  doc/diagram/maintanence.txt
  doc/diagram/software_upgrade.txt
  doc/img/maintanence.png
  doc/img/software_upgrade.png
  doc/rendszerterv.md
Labels: documentation

#54 System Design [9] - Database Design
  doc/img/scheme.png
  doc/rendszerspec.md
  doc/rendszerterv.md
Labels: documentation

#55 Added the eleventh chapter of the system spec. Closes #40
  doc/rendszerterv.md
Labels: documentation

#57 Rendszerterv [3] - Üzleti folyamatok modellje
  doc/diagram/admin_berles.txt
  doc/diagram/admin_felhasznalo.txt
  doc/img/admin_berles.png
  doc/img/admin_felhasznalo.png
  doc/rendszerterv.md
Labels: documentation

#56 Created paragraph 4 of the system spec. Closes #33
  doc/rendszerterv.md
Labels: documentation

#46 Funkspec jelenlegi
  doc/funkspec.md
Labels: documentation

#59 Rendszerterv absztrakt domain modell Closes #36
  doc/img/absztrakt_komp.png
  doc/rendszerterv.md
Labels: documentation

#62 Rendszerterv Architekturális Terv
  doc/img/rendszerterv_architectural_plan.png
  doc/rendszerterv.md
Labels: documentation

#50 Rendszerterv Fizikai Környezet
  doc/rendszerterv.md
Labels: documentation

#63 Write használati esetek
  doc/funkspec.md
Labels: documentation

#74 Base code for the admin. Closes #64
  admin/.gitignore
  admin/README.md
  admin/db.json
  admin/package-lock.json
  admin/package.json
  admin/public/favicon.ico
  admin/public/index.html
  admin/public/logo192.png
  admin/public/logo512.png
  admin/public/manifest.json
  admin/public/robots.txt
  admin/src/App.css
  admin/src/App.js
  admin/src/App.test.js
  admin/src/index.css
  admin/src/index.js
  admin/src/logo.svg
  admin/src/serviceWorker.js
  admin/src/setupTests.js
Labels: enhancement

#76 Created the UserList Component for the Admin UI
  admin/db.json
  admin/package.json
  admin/src/App.js
  admin/src/components/UserList.js
Labels: enhancement

#78 Created the RentList Component for the Admin UI.
  admin/src/App.js
  admin/src/components/RentList.js
Labels: enhancement

#77 Created the UserEdit component for the Admin UI.
  admin/src/App.js
  admin/src/components/UserEdit.js
Labels: enhancement

#82 Created "CarEdit component."
  admin/src/App.js
  admin/src/components/CarEdit.js
  admin/src/components/CarList.js
Labels: enhancement

#79 Created "CarList component."
  admin/src/App.js
  admin/src/components/CarList.js
Labels: enhancement
