Repository krook1024/SZFM_2020_1_KP_B1G, pull requests merged in 2020-11, with the labels that each got.

#90 Initialized the context. Initialized the CarList component for an example.
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/client/CarList.js
  client/src/context/rental-context.js
  client/src/pages/HomePage.js
Labels: enhancement

#80 Admin UserCreate
  client/src/components/admin/UserCreate.js
  client/src/components/admin/UserEdit.js
  client/src/pages/AdminPage.js
Labels: enhancement

#81 Admin CarCreate
  client/src/components/admin/CarCreate.js
  client/src/pages/AdminPage.js
Labels: enhancement

#93 Remove unused changes
  client/src/components/admin/CarCreate.js
Labels: bug, fix

#91 Registration Component
  client/src/components/client/Registration.js
Labels: enhancement

#95 User Frontend - Car Card Komponens
  .gitignore
  client/src/components/client/Car.js
  client/src/pages/HomePage.js
Labels: enhancement

#94 Login Komponens Frontend része
  .gitignore
  client/src/components/client/Login.js
  client/src/pages/HomePage.js
Labels: enhancement

#105 User frontend - Header komponens
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/client/NavBar.js
  client/src/components/client/Registration.js
  client/src/pages/AdminPage.js
  client/src/pages/HomePage.js
Labels: enhancement

#106 Frontend - CarRent Modal
  client/db.json
  client/src/components/client/Car.js
  client/src/components/client/CarRent.js
Labels: enhancement

#112 Started working on the backend.
  .env.example
  .gitignore
  controllers/authController.js
  controllers/carController.js
  controllers/userController.js
  docker-compose.yml
  docker_start.sh
  filldb.js
  index.js
  models/Car.js
  models/Rent.js
  models/User.js
  package-lock.json
  package.json
  routes/auth.js
  routes/cars.js
  routes/index.js
  routes/users.js
Labels: enhancement

#113 Code style and other improvements in the project generally.
  client/package.json
  client/src/components/client/Car.js
  client/src/components/client/CarList.js
  client/src/components/client/Login.js
  client/src/components/client/NavBar.js
  client/src/pages/HomePage.js
  index.js
  package-lock.json
  package.json
Labels: bug

#117 Fixed the image size bug in CarRent Modal.
  client/src/components/client/CarRent.js
Labels: fix

#118 CRUD methods for Unprotected routes
  controllers/carController.js
  controllers/userController.js
  routes/cars.js
  routes/users.js
Labels: enhancement

#119 Authentication on the server side. Closes #103
  controllers/authAdminStrategy.js
  controllers/authController.js
  controllers/authStrategy.js
  models/User.js
  routes/auth.js
Labels: enhancement

#120 Authprovider implemented for react-admin. Closes #110.
  client/src/admin/authProvider.js
  client/src/pages/AdminPage.js
Labels: enhancement

#121 Rents route CRUD methods implemented, test rents added to db.
  controllers/rentController.js
  filldb.js
  index.js
  models/Rent.js
  routes/rents.js
Labels: enhancement

#122 findAll methods Fix in controllers.
  controllers/carController.js
  controllers/rentController.js
  controllers/userController.js
Labels: fix

#123 Demo files upload
  doc/demo/demo.md
  doc/demo/demo_final.pdf
  doc/demo/demo_origin.pdf
  doc/demo/demo_pics/admin_cars.png
  doc/demo/demo_pics/admin_create_car.png
  doc/demo/demo_pics/admin_create_user.png
  doc/demo/demo_pics/admin_edit_car.png
  doc/demo/demo_pics/admin_edit_user.png
  doc/demo/demo_pics/admin_login.png
  doc/demo/demo_pics/admin_rents.png
  doc/demo/demo_pics/admin_users.png
  doc/demo/demo_pics/cars-listed.png
  doc/demo/demo_pics/client_cars_list.png
  doc/demo/demo_pics/client_login.png
  doc/demo/demo_pics/client_rent.png
  doc/demo/demo_pics/home.png
  doc/demo/demo_pics/login.png
  doc/demo/demo_pics/register.png
  doc/demo/demo_pics/rent-car.png
Labels: documentation

#132 Protect existing routes. Closes #124
  routes/cars.js
  routes/rents.js
  routes/users.js
Labels: enhancement

#137 User Frontend - Auth context
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/client/Login.js
  client/src/components/client/NavBar.js
  client/src/context/user-context.js
  client/src/pages/HomePage.js
  client/src/pages/Profile.js
Labels: enhancement

#140 Backend - Only list not rented cars
  client/src/pages/HomePage.js
  controllers/carController.js
  docker_stop.sh
  routes/cars.js
Labels: enhancement
